name: Build and Push to ECR
on:
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials (access keys)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repo
        run: |
          aws ecr describe-repositories --repository-names ccfd-repo --region us-east-1 >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name ccfd-repo --region us-east-1

      - name: Build and push image
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker build -t "$ECR_REGISTRY/ccfd-repo:latest" -f Dockerfile .
          docker push "$ECR_REGISTRY/ccfd-repo:latest"

      - name: Print image URI
        run: echo "IMAGE_URI=${{ steps.login-ecr.outputs.registry }}/ccfd-repo:latest"
