name: Build and Push to ECR
on: { workflow_dispatch: {} }
env:
  AWS_REGION: us-east-1
  ECR_REPO:  ccfd-repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        id: aws-creds
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - name: Who am I (account check)
        run: aws sts get-caller-identity

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Ensure ECR repo
        run: |
          aws ecr describe-repositories --repository-names "$ECR_REPO" >/dev/null 2>&1 || \
          aws ecr create-repository --repository-name "$ECR_REPO"

      - name: Build and push
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "Registry: $ECR_REGISTRY"
          docker build -t "$ECR_REGISTRY/$ECR_REPO:latest" -f Dockerfile .
          docker push "$ECR_REGISTRY/$ECR_REPO:latest"

      - name: Summary
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          echo "### Account & Registry" >> $GITHUB_STEP_SUMMARY
          aws sts get-caller-identity >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Image URI" >> $GITHUB_STEP_SUMMARY
          echo "$ECR_REGISTRY/$ECR_REPO:latest" >> $GITHUB_STEP_SUMMARY
