name: Python CI
on: [push, pull_request]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Import smoke test
        run: |
          python - << 'PY'
          import importlib
          for m in ["pandas","numpy","sklearn","joblib","streamlit","shap"]:
              importlib.import_module(m)
          print("✅ imports ok")
          PY
      - name: Verify optional config presence
        run: |
          python - << 'PY'
          from pathlib import Path
          p = Path("artifacts/config.json")
          print("config exists:", p.exists())
          PY
