name: Build and Push to ECR
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Extract short SHA
        id: vars
        run: echo "SHA7=$(echo ${GITHUB_SHA} | cut -c1-7)" >> $GITHUB_OUTPUT

      - name: Build image
        run: docker build -t ${{ steps.ecr.outputs.registry }}/ccfd-repo:latest -t ${{ steps.ecr.outputs.registry }}/ccfd-repo:${{ steps.vars.outputs.SHA7 }} .

      - name: Push image
        run: |
          docker push ${{ steps.ecr.outputs.registry }}/ccfd-repo:latest
          docker push ${{ steps.ecr.outputs.registry }}/ccfd-repo:${{ steps.vars.outputs.SHA7 }}
