name: Build and Push to ECR

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - "app/**"
      - "Dockerfile"
      - "requirements.txt"
      - "artifacts/**"
      - ".github/workflows/ecr_push.yaml"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ECR_REPO: ccfd-repo

    steps:
      - uses: actions/checkout@v4

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id:     ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region:            ${{ env.AWS_REGION }}

      - id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and push :latest and :sha7
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          GIT_SHA: ${{ github.sha }}
        run: |
          SHORT_SHA=${GIT_SHA::7}
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV

          docker build -t "$ECR_REGISTRY/$ECR_REPO:latest" -t "$ECR_REGISTRY/$ECR_REPO:$SHORT_SHA" -f Dockerfile .
          docker push "$ECR_REGISTRY/$ECR_REPO:latest"
          docker push "$ECR_REGISTRY/$ECR_REPO:$SHORT_SHA"

          {
            echo "### Pushed images"
            echo "- \`$ECR_REGISTRY/$ECR_REPO:latest\`"
            echo "- \`$ECR_REGISTRY/$ECR_REPO:$SHORT_SHA\`"
          } >> $GITHUB_STEP_SUMMARY
